version: '2'
services:

  vista: 
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/var/www/html

  bd:
    container_name: BD
    image: mysql:5.7
    tty: true
    ports:
      - "3305:3306"
    restart: unless-stopped 
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=usuario
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=base
    volumes:
      - ./db/mysql:/var/lib/mysql

  reservas:
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./reservas:/var/www/html

  login:
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./login:/var/www/html

  backoffice:
    build:
      context: ./
    tty: true
    restart: unless-stopped
    ports:
      - "8083:80"
    volumes:
      - ./backoffice:/var/www/html